### ISSUE TITLE
Add coverage and credo to project

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth-mvp#9]
Monitor the code of the project with
- [x] coverage: https://github.com/parroty/excoveralls
- [x] credo: https://hexdocs.pm/credo/Credo.html

**Comment by SimonLab** [comment]
see also https://github.com/dwyl/app-mvp-phoenix/issues/21

- updating .travis.yml to run `cover` instead of just `test`. This will run the tests + create the coverage json report which is then send to codecov.

```yml
script:
  - mix cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
```
